### ISSUE TITLE
xrstf/ip-utils is dead #rip

### ISSUE THREAD

**Issue by Meinder-A** [Jalle19/php-whitelist-check#11]
Hello,

Dependency "xrstf/ip-utils" is not accessible anymore (https://bitbucket.org/xrstf/ip-utils) due to the fact that BitBucket decided to stop supporting Mercurial (https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket).

**Comment by glorpen** [comment]
Until it is fixed (in this and other repos..) you can define ip-utils composer repo as https://bitbucket.org/glorpen/ip-utils/src/default/

**Comment by jycr753** [comment]
prop fix at #12

**Comment by Meinder-A** [comment]
had to use something else so it could deploy

if anyone is interested: https://github.com/mlocati/ip-lib

**Comment by Jalle19** [comment]
Fixed in https://github.com/Jalle19/php-whitelist-check/pull/12 , tagged as 1.1.0
